### ISSUE TITLE
Don't work with MIUI 14

### ISSUE THREAD

**Issue by ARHCOS** [Hamza417/SystemLauncher#4]
The latest release makes the device bootlooping with MIUI 14 phones

**Comment by Hamza417** [comment]
@ARHCOS I'll update it in a moment.

**Comment by Hamza417** [comment]
Updated [Here](https://github.com/Hamza417/SystemLauncher/releases/tag/RELEASE-4.39.5.5832-12261744).

**Comment by ARHCOS** [comment]
Thank you so much
